insert into Music(artistName,albumName,numberSold,cost) values ('Mozart','Greatest Hits',100000,10);

insert into Music(artistName,albumName,numberSold,cost) values ('Taylor Swift','Fearless',2300000,15);

insert into Music(artistName,albumName,numberSold,cost) values ('Black Sabbath','Paranoid',534000,12);

insert into Music(artistName,albumName,numberSold,cost) values ('Katy Perry','Prism',800000,16);

insert into Music(artistName,albumName,numberSold,cost) values ('Katy Perry','Teenage Dream',750000,14);
